deploy:
  type: git
  repo: git@github.com:sunny73/sunny73.github.io.git
  branch: master

theme: next


# site
title: YingLiu's blog
subtitle: YingLiu
description: Find Yourself
keywords:
author: YingLiu 
language: en
timezone: ''