deploy:
  type: git
  repo: git@github.com:sunny73/sunny73.github.io.git
  branch: master

theme: next


# site
title: YingLiu's Blog
subtitle: 追风之人
description: Find Yourself
keywords:
author: YingLiu 
language: en
timezone: ''





#添加站内搜索按钮
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

symbols_count_time:
 #文章内是否显示
  symbols: true
  time: true
 # 网页底部是否显示
  total_symbols: true
  total_time: true

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-ni-j
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true


highlight:
  enable: true #是否开启代码高亮
  line_number: true #是否增加代码行号
  auto_detect: true #自动判断代码语言
  tab_replace: ""
  wrap: true
  hljs: false

