deploy:
  type: git
  repo: git@github.com:sunny73/sunny73.github.io.git
  branch: master

theme: next


# site
title: YingLiu's blog
subtitle: YingLiu
description: Find Yourself
keywords:
author: YingLiu 
language: en
timezone: ''





#添加站内搜索按钮
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

symbols_count_time:
 #文章内是否显示
  symbols: true
  time: true
 # 网页底部是否显示
  total_symbols: true
  total_time: true